/// <reference types="vite/client" />
import { initializeApp, getApps, getApp, FirebaseApp } from 'firebase/app';
import { getFirestore, Firestore, doc, getDocFromServer } from 'firebase/firestore';
import { getAuth, Auth } from 'firebase/auth';

// Default / fallback Firebase config template
const defaultFirebaseConfig = {
  apiKey: import.meta.env.VITE_FIREBASE_API_KEY || "AIzaSyDemoConfigKeyForNextEnergyAndAcademyDashboard",
  authDomain: import.meta.env.VITE_FIREBASE_AUTH_DOMAIN || "next-coo-dashboard.firebaseapp.com",
  projectId: import.meta.env.VITE_FIREBASE_PROJECT_ID || "next-coo-dashboard",
  storageBucket: import.meta.env.VITE_FIREBASE_STORAGE_BUCKET || "next-coo-dashboard.appspot.com",
  messagingSenderId: import.meta.env.VITE_FIREBASE_MESSAGING_SENDER_ID || "1034522784368",
  appId: import.meta.env.VITE_FIREBASE_APP_ID || "1:1034522784368:web:a1b2c3d4e5f6",
};

let appletConfig = defaultFirebaseConfig;

try {
  // Try dynamic import of firebase-applet-config.json if generated by set_up_firebase
  const globConfig = import.meta.glob('/firebase-applet-config.json', { eager: true });
  const configKeys = Object.keys(globConfig);
  if (configKeys.length > 0) {
    const loadedObj = (globConfig[configKeys[0]] as any)?.default || globConfig[configKeys[0]];
    if (loadedObj && loadedObj.projectId) {
      appletConfig = { ...defaultFirebaseConfig, ...loadedObj };
    }
  }
} catch {
  // Fallback to default
}

export const firebaseApp: FirebaseApp = getApps().length === 0 ? initializeApp(appletConfig) : getApp();
export const db: Firestore = getFirestore(firebaseApp);
export const auth: Auth = getAuth(firebaseApp);

export async function testFirestoreConnection(): Promise<boolean> {
  try {
    await getDocFromServer(doc(db, 'system', 'connection_test'));
    return true;
  } catch (error) {
    if (error instanceof Error && error.message.includes('offline')) {
      console.warn("Firestore client is in offline mode or waiting for configuration.");
    } else {
      console.warn("Firestore connection check:", error);
    }
    return false;
  }
}

export enum OperationType {
  CREATE = 'create',
  UPDATE = 'update',
  DELETE = 'delete',
  LIST = 'list',
  GET = 'get',
  WRITE = 'write',
}

export interface FirestoreErrorInfo {
  error: string;
  operationType: OperationType;
  path: string | null;
  authInfo: {
    userId?: string | null;
    email?: string | null;
    emailVerified?: boolean | null;
    isAnonymous?: boolean | null;
  };
}

export function handleFirestoreError(error: unknown, operationType: OperationType, path: string | null) {
  const errInfo: FirestoreErrorInfo = {
    error: error instanceof Error ? error.message : String(error),
    authInfo: {
      userId: auth.currentUser?.uid || null,
      email: auth.currentUser?.email || null,
      emailVerified: auth.currentUser?.emailVerified || null,
      isAnonymous: auth.currentUser?.isAnonymous || null,
    },
    operationType,
    path,
  };
  console.error('Firestore Operation Error: ', JSON.stringify(errInfo));
  throw new Error(JSON.stringify(errInfo));
}
